# Generated by Django 4.2.23 on 2025-08-28 07:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Име')),
                ('attachment', models.FileField(upload_to='docs/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, default='', help_text='Съкратено име на училището', max_length=20, verbose_name='Абревиатура')),
                ('full_name', models.TextField(blank=True, default='', help_text='Пълно име на училището', verbose_name='Име')),
                ('city', models.CharField(blank=True, default='', help_text='Населено място, където се намира училището', max_length=50, verbose_name='Населено място')),
                ('logo', models.ImageField(blank=True, upload_to=main.models.school_pic_path, verbose_name='Лого')),
                ('address', models.CharField(blank=True, default='', help_text='Адрес в населеното място (ул. ... №...)', max_length=50, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, default='', max_length=35, verbose_name='e-mail')),
                ('boss', models.CharField(blank=True, default='', help_text='Име на директора на училището', max_length=50, verbose_name='Директор')),
            ],
            options={
                'verbose_name': 'Училище/организация',
                'verbose_name_plural': 'Училища/организации',
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_num', models.CharField(blank=True, default='', max_length=8, verbose_name='Специалност - номер')),
                ('specialty_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Специалност - име')),
                ('plan', models.FileField(upload_to='docs/', verbose_name='Учебен план')),
                ('level', models.PositiveSmallIntegerField(choices=[(2, 'втора'), (3, 'трета')], default=3, help_text='Степен на професионална квалификация')),
            ],
            options={
                'verbose_name': 'Специалност',
                'verbose_name_plural': 'Специалности',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(choices=[(True, 'мъж'), (False, 'жена')], default=True, verbose_name='Пол')),
                ('access_level', models.PositiveSmallIntegerField(choices=[(1, 'Системен администратор'), (2, 'НАБЛЮДАВАЩ АДМИНИСТРАТОР'), (3, 'УЧИЛИЩЕН АДМИНИСТРАТОР'), (4, 'УЧИТЕЛ'), (5, 'УЧЕНИК')], default=5, help_text='роля (ниво на достъп)', verbose_name='Роля')),
                ('session_screen', models.PositiveSmallIntegerField(choices=[(1, 'тъмна'), (2, 'светла')], default=1, help_text='цветова схема на интерфейса', verbose_name='Интерфейс')),
                ('klas', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)], verbose_name='Клас')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_school', to='main.school', verbose_name='училище')),
                ('speciality', models.ForeignKey(blank=True, help_text='специалност по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_speciality', to='main.specialty', verbose_name='Специалност')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пофил на потребител',
                'verbose_name_plural': 'Пофили на потребител',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='main.specialty', verbose_name='Специалности'),
        ),
    ]
