# Generated by Django 4.2.23 on 2025-08-28 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='id на потребител')),
                ('user_name', models.CharField(default='', max_length=50, null=True, verbose_name='име на потребител')),
                ('action', models.CharField(default='', max_length=200, verbose_name='Действие')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='дата и час')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
        ),
    ]
