# Generated by Django 4.2.24 on 2025-09-04 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='grade_section',
            field=models.ForeignKey(blank=True, help_text='клас по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_grade', to='main.klass', verbose_name='Клас'),
        ),
    ]
