# Generated by Django 4.2.24 on 2025-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_grade_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='classes',
            field=models.ManyToManyField(blank=True, to='main.klass', verbose_name='Класове'),
        ),
    ]
