# Generated by Django 4.2.24 on 2025-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='plan',
            field=models.FileField(blank=True, upload_to='docs/', verbose_name='Учебен план'),
        ),
    ]
