# Generated by Django 4.2.24 on 2025-09-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_school_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='plan',
        ),
    ]
