# Generated by Django 4.2.24 on 2025-09-04 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_specialty_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='klas',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, default=11, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)], verbose_name='Клас'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, default='а', max_length=1, null=True, verbose_name='Паралелка'),
        ),
    ]
