# Generated by Django 4.2.24 on 2025-09-06 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_specialty_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
                ('grade', models.SmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)], verbose_name='Клас')),
                ('subject_type', models.BooleanField(choices=[(True, 'теория'), (False, 'практика')], default=True, verbose_name='Тип')),
                ('hpy', models.PositiveIntegerField(default=54, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Брой часове годишно')),
                ('wpy', models.SmallIntegerField(choices=[(11, 11), (18, 18), (27, 27), (29, 29), (36, 29)], default=18, verbose_name='Брой учебни седмици годишно')),
                ('hpw1', models.SmallIntegerField(default=0, verbose_name='Брой часове седмично (1-ви срок)')),
                ('hpw2', models.SmallIntegerField(default=0, verbose_name='Брой часове седмично (2-ри срок)')),
            ],
            options={
                'verbose_name': 'Учебен предмет',
                'verbose_name_plural': 'Учебни предмети',
            },
        ),
        migrations.AddField(
            model_name='specialty',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='main.subject', verbose_name='Предмети'),
        ),
    ]
