# Generated by Django 4.2.24 on 2025-09-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_subject_specialty_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='учебен предмет по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subject', to='main.subject', verbose_name='Предмет'),
        ),
    ]
