# Generated by Django 4.2.24 on 2025-09-07 21:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_userprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='goals',
            field=models.TextField(blank=True, default='', help_text='Цели на обучението по предмета', verbose_name='Цели'),
        ),
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.TextField(blank=True, default='', help_text='Задачи на обучението по предмета', verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='wpy',
            field=models.SmallIntegerField(choices=[(11, 11), (18, 18), (27, 27), (29, 29), (36, 36)], default=18, verbose_name='Брой учебни седмици годишно'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Раздел №')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_id', to='main.subject')),
            ],
            options={
                'verbose_name': 'Раздел от УП',
                'verbose_name_plural': 'Раздели от УП',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Раздел №')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
                ('MoSCoW_cat', models.CharField(blank=True, choices=[('M', 'must'), ('S', 'should'), ('C', 'could'), ('W', 'won`t')], default='', max_length=1, verbose_name='MoSCoW категория')),
                ('MoSCoW_rem', models.CharField(blank=True, default='', max_length=200, verbose_name='MoSCoW обосновка')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_id', to='main.unit')),
            ],
            options={
                'verbose_name': 'Тема от раздел на УП',
                'verbose_name_plural': 'Теми от раздел на УП',
            },
        ),
    ]
