# Generated by Django 4.2.24 on 2025-09-08 06:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subject_creator_subject_goals_subject_objectives_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='hours',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мин. брой часове'),
        ),
    ]
