# Generated by Django 4.2.24 on 2025-09-09 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_unit_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Раздел №')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Цел на обучението',
                'verbose_name_plural': 'Цели на обучението',
            },
        ),
        migrations.CreateModel(
            name='Objectives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Раздел №')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
            ],
            options={
                'verbose_name': 'Задачa на обучението',
                'verbose_name_plural': 'Задачи на обучението',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Раздел №')),
                ('name', models.CharField(max_length=200, verbose_name='Име')),
                ('MoSCoW_cat', models.CharField(blank=True, choices=[('M', 'must'), ('S', 'should'), ('C', 'could'), ('W', 'won`t')], default='', max_length=1, verbose_name='MoSCoW категория')),
                ('MoSCoW_rem', models.CharField(blank=True, default='', max_length=200, verbose_name='MoSCoW обосновка')),
            ],
            options={
                'verbose_name': 'Тема от раздел на УП',
                'verbose_name_plural': 'Теми от раздел на УП',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='objectives',
        ),
        migrations.AlterField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_subject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_unit', to='main.subject'),
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
        migrations.AddField(
            model_name='topic',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_topic', to='main.unit'),
        ),
        migrations.AddField(
            model_name='objectives',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_objectives', to='main.subject'),
        ),
        migrations.AddField(
            model_name='goals',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_goals', to='main.subject'),
        ),
    ]
