# Generated by Django 4.2.24 on 2025-09-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_goals_objectives_topic_remove_subject_goals_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='Objectives',
            new_name='Objective',
        ),
    ]
