# Generated by Django 4.2.24 on 2025-09-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_goals_goal_rename_objectives_objective'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
