# Generated by Django 4.2.24 on 2025-09-13 11:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Занятие №')),
                ('name', models.CharField(help_text='Общо име на занятието', max_length=200, verbose_name='Име')),
                ('focus', models.TextField(blank=True, default='', help_text='Фокус(основни акценти на занятието', verbose_name='Фокус')),
                ('goals', models.TextField(blank=True, default='', help_text='Оосновни цели на занятието', verbose_name='Цели')),
                ('duration', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Продължителност')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_session', to='main.subject')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='SessionTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Описание')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_topics', to='main.session', verbose_name='Занятие')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_sessions', to='main.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Занятие (тема)',
                'verbose_name_plural': 'Занятие (теми)',
            },
        ),
        migrations.AddConstraint(
            model_name='sessiontopics',
            constraint=models.UniqueConstraint(fields=('session', 'topic'), name='unique_session_topic'),
        ),
    ]
