# Generated by Django 4.2.24 on 2025-09-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_session_sessiontopics_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionTopics',
            new_name='SessionTopic',
        ),
    ]
