# Generated by Django 4.2.24 on 2025-09-16 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_sessiontopics_sessiontopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['num', 'id'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AddField(
            model_name='session',
            name='unit',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='unit_session', to='main.unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='focus',
            field=models.TextField(blank=True, default='', help_text='Фокус(основни акценти на занятието)', verbose_name='Фокус'),
        ),
    ]
