# Generated by Django 4.2.24 on 2025-09-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_session_options_session_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='unit',
        ),
    ]
