# Generated by Django 4.2.24 on 2025-09-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_session_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='basic_level',
            field=models.BooleanField(choices=[(True, 'Основно(задължително) занятие'), (False, 'Резервно(при необходимост) занятие')], default=True, verbose_name='Тип на занятието'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(blank=True, choices=[('НЗ', 'Нови знания'), ('УПР', 'Упражнение'), ('ПК', 'Проверка и контрол'), ('ОС', 'Обобщаване и систематизиране'), ('K', 'Комбиниран урок')], default='', max_length=3, verbose_name='Вид на урочната единица'),
        ),
    ]
