# Generated by Django 4.2.24 on 2025-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_session_basic_level_session_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='collapsed',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Не')], default=True, verbose_name='Показва се "свито"'),
        ),
    ]
