# Generated by Django 4.2.24 on 2025-09-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_session_collapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session',
            field=models.ForeignKey(blank=True, help_text='занятие по подразбиране', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_session', to='main.session', verbose_name='Занятие'),
        ),
    ]
