# Generated by Django 4.2.24 on 2025-09-22 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userprofile_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontopic',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Съдържание на точката (html)', verbose_name='Съдържание'),
        ),
        migrations.CreateModel(
            name='SessionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Текст(име)')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Описание')),
                ('duration', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)], verbose_name='Продължителност (мин.)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_points', to='main.session', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Точка от плана',
                'verbose_name_plural': 'Точки от плана',
            },
        ),
    ]
