# Generated by Django 4.2.24 on 2025-09-22 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sessiontopic_content_sessionpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpoint',
            name='num',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Занятие №'),
        ),
    ]
