# Generated by Django 4.2.24 on 2025-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sessionpoint_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiontopic',
            name='content',
        ),
        migrations.AddField(
            model_name='sessionpoint',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Съдържание на точката (html)', verbose_name='Съдържание'),
        ),
    ]
