# Generated by Django 4.2.24 on 2025-09-24 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_sessiontopic_content_sessionpoint_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionpoint',
            name='duration',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(270)], verbose_name='Продължителност (мин.)'),
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Бележка №')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Текст(име)')),
                ('condition', models.TextField(blank=True, default='', help_text='Условие на задачата (html)', verbose_name='Условие')),
                ('answer', models.TextField(blank=True, default='', help_text='Отговор на задачата (html)', verbose_name='Орговор')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_tasks', to='main.sessionpoint', verbose_name='Задача към точка от план')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='main.session', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Задача към точка от план',
                'verbose_name_plural': 'Задачи към точка от план',
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Бележка №')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Текст(име)')),
                ('content', models.TextField(blank=True, default='', help_text='Съдържание на точката (html)', verbose_name='Съдържание')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_notes', to='main.sessionpoint', verbose_name='Точка от плана на урока')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='main.session', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Бележка към точка от план',
                'verbose_name_plural': 'Бележки към точка от план',
            },
        ),
    ]
