# Generated by Django 4.2.24 on 2025-10-04 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_sessionpoint_duration_sessiontask_sessionnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade_section',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='grade',
            field=models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)], verbose_name='Клас'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(default='а', max_length=1, validators=[django.core.validators.MinValueValidator('а'), django.core.validators.MaxValueValidator('я')], verbose_name='Паралелка'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='session',
            field=models.ForeignKey(blank=True, help_text='занятие по подразбиране', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_session', to='main.session', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='speciality',
            field=models.ForeignKey(blank=True, help_text='специалност по подразбиране', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_speciality', to='main.specialty', verbose_name='Специалност'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='учебен предмет по подразбиране', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subject', to='main.subject', verbose_name='Предмет'),
        ),
        migrations.DeleteModel(
            name='Klass',
        ),
    ]
