# Generated by Django 4.2.24 on 2025-10-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_school_classes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('теория', 'теория'), ('практика', 'практика')], default='теория', max_length=10, verbose_name='Тип'),
        ),
    ]
