# Generated by Django 4.2.24 on 2026-09-09 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['num', 'id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроци'},
        ),
        migrations.AlterModelOptions(
            name='sessiontopic',
            options={'verbose_name': 'Урок (тема)', 'verbose_name_plural': 'Урок (теми)'},
        ),
        migrations.AddField(
            model_name='specialty',
            name='specialty_type',
            field=models.CharField(choices=[('професия', 'професия'), ('специалност', 'специалност')], default='специалност', max_length=15, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='session',
            name='basic_level',
            field=models.BooleanField(choices=[(True, 'Основен(задължителен) урок'), (False, 'Резервен(при необходимост) урок')], default=True, verbose_name='Тип на урока'),
        ),
        migrations.AlterField(
            model_name='session',
            name='focus',
            field=models.TextField(blank=True, default='', help_text='Фокус(основни акценти на урока)', verbose_name='Фокус'),
        ),
        migrations.AlterField(
            model_name='session',
            name='goals',
            field=models.TextField(blank=True, default='', help_text='Оосновни цели на урока', verbose_name='Цели'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(help_text='Общо име на урока', max_length=200, verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='session',
            name='num',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Урок №'),
        ),
    ]
