# Generated by Django 4.2.24 on 2026-09-11 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_session_options_alter_sessiontopic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Приложение №')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Текст(име)')),
                ('content', models.TextField(blank=True, default='', help_text='Съдържание на приложението (html)', verbose_name='Съдържание')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_attachments', to='main.sessionpoint', verbose_name='Точка от плана на урока')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attachments', to='main.session', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Приложение към точка от план',
                'verbose_name_plural': 'Приложения към точка от план',
            },
        ),
    ]
