# Generated by Django 4.2.24 on 2026-09-11 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_sessionattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionattachment',
            options={'ordering': ['num', 'id'], 'verbose_name': 'Приложение / Файл към занятие', 'verbose_name_plural': 'Приложения / Файлове към занятие'},
        ),
        migrations.RemoveField(
            model_name='sessionattachment',
            name='content',
        ),
        migrations.AddField(
            model_name='sessionattachment',
            name='attachment_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('other', 'Други')], default='other', max_length=20, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='sessionattachment',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Коментар или описание на файла', verbose_name='Коментар / Описание'),
        ),
        migrations.AddField(
            model_name='sessionattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='session_attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Име / Заглавие'),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='num',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№'),
        ),
    ]
