# Generated by Django 4.2.24 on 2026-09-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_sessionattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='MoSCoW_rem',
            field=models.TextField(blank=True, default='', verbose_name='MoSCoW обосновка'),
        ),
    ]
