# Generated by Django 4.2.24 on 2026-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_topic_moscow_rem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_day_start', models.CharField(default='08:00', help_text='Начален час във формат HH:MM (напр. 08:00)', max_length=5, verbose_name='Начален час на първия учебен час')),
                ('school_lessons_count', models.PositiveSmallIntegerField(default=7, help_text='Брой учебни часове в рамките на един учебен ден', verbose_name='Брой учебни часове дневно')),
                ('lesson_duration_minutes', models.PositiveSmallIntegerField(default=45, help_text='Продължителност на един учебен час в минути', verbose_name='Продължителност на учебния час (минути)')),
                ('first_break_duration_minutes', models.PositiveSmallIntegerField(default=20, help_text='Продължителност на първото (голямо) междучасие в минути', verbose_name='Продължителност на първото междучасие (минути)')),
                ('regular_break_duration_minutes', models.PositiveSmallIntegerField(default=10, help_text='Продължителност на останалите (малки) междучасия в минути', verbose_name='Продължителност на останалите междучасия (минути)')),
            ],
            options={
                'verbose_name': 'Параметри на учебния ден',
                'verbose_name_plural': 'Параметри на учебния ден',
            },
        ),
    ]
