# Generated by Django 4.2.24 on 2026-09-13 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0029_schooldayconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие / Име')),
                ('page_key', models.CharField(choices=[('general', 'Общи промптове'), ('course_goals', 'Цели на курс/предмет'), ('course_units', 'Учебни раздели/модули'), ('course_lessons', 'Теми за уроци'), ('session_list', 'Списък с уроци'), ('lesson_main', 'Подготовка на урок / занятие'), ('school_day', 'Учебен ден и програма')], db_index=True, default='general', max_length=50, verbose_name='Страница / Контекст')),
                ('prompt_text', models.TextField(help_text='Поддържа плейсхолдъри: {предмет}, {тема}, {цели}, {фокус}, {точки}, {клас}, {специалност}', verbose_name='Текст на промпта')),
                ('instructions', models.TextField(blank=True, default='', help_text='Препоръки за очакван резултат и настройки на AI модела', verbose_name='Указания за ползване')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системен шаблон')),
                ('order', models.SmallIntegerField(default=1, verbose_name='Подредба')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновен на')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts', to=settings.AUTH_USER_MODEL, verbose_name='Създаден от')),
            ],
            options={
                'verbose_name': 'AI Промпт',
                'verbose_name_plural': 'AI Промптове',
                'ordering': ['page_key', 'order', 'title'],
            },
        ),
    ]
