# Generated by Django 4.2.24 on 2026-09-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_seed_python_stack_curriculum_prompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name', '-subject_type'], 'verbose_name': 'Учебен предмет', 'verbose_name_plural': 'Учебни предмети'},
        ),
    ]
