# Generated by Django 4.2.24 on 2026-09-17 21:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_subject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='№')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Име / Заглавие')),
                ('file', models.FileField(blank=True, null=True, upload_to='app_attachments/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, default='', help_text='Коментар или описание на файла', verbose_name='Коментар / Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Създаден на')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновен на')),
            ],
            options={
                'verbose_name': 'Приложение / Файл',
                'verbose_name_plural': 'Приложения / Файлове',
                'ordering': ['num', 'id'],
            },
        ),
    ]
