# Generated by Django 4.2.24 on 2026-09-18 22:27

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_fix_grade_12_term_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprompt',
            name='prompt_text',
            field=models.TextField(help_text='Поддържа плейсхолдъри: {предмет}, {тема}, {цели}, {фокус}, {точки}, {клас}, {специалност}, {списък_уроци}, {раздели_и_теми}, {структура_часове}', verbose_name='Текст на промпта'),
        ),
        migrations.AlterField(
            model_name='appattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.utils.app_attachment_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='attachment',
            field=models.FileField(upload_to=main.utils.document_upload_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=main.utils.session_attachment_upload_path, verbose_name='Файл'),
        ),
    ]
