# Generated by Django 4.2.24 on 2026-09-21 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0044_unique_ascii_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='appattachment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Създаден от'),
        ),
        migrations.AddField(
            model_name='appattachment',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системен файл / приложение'),
        ),
    ]
