# Generated by Django 4.2.24 on 2026-09-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_appattachment_created_by_appattachment_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='appattachment',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Оригинално име на файла'),
        ),
    ]
