# Generated by Django 4.2.24 on 2026-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_appattachment_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattachment',
            name='original_filename',
            field=models.CharField(blank=True, default='', help_text='Оригинално име на качения файл преди промяна', max_length=255, verbose_name='Оригинално име на файла'),
        ),
    ]
