# Generated by Django 4.2.24 on 2026-09-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_seed_lesson_evaluation_rubric_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattachment',
            name='is_student_visible',
            field=models.BooleanField(default=True, help_text='Указва дали файлът е видим за учениците', verbose_name='Видимо за учениците'),
        ),
    ]
