# Generated by Django 4.2.24 on 2026-09-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_seed_lesson_micro_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='social_emotional_goals',
            field=models.TextField(blank=True, default='', help_text='Социално-емоционални цели / умения на 21. век', verbose_name='Социално-емоционални цели'),
        ),
        migrations.AlterField(
            model_name='aiprompt',
            name='prompt_text',
            field=models.TextField(help_text='Поддържа плейсхолдъри: {предмет}, {тема}, {цели}, {социално_емоционални_цели}, {фокус}, {точки}, {клас}, {специалност}, {списък_уроци}, {раздели_и_теми}, {структура_часове}', verbose_name='Текст на промпта'),
        ),
        migrations.AlterField(
            model_name='sessionattachment',
            name='attachment_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('worksheet', 'Работен лист'), ('rubric', 'Оценъчна карта / Чек-лист'), ('exit_ticket', 'Изходен билет'), ('other', 'Други')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
