# Generated by Django 4.2.24 on 2026-09-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_session_social_emotional_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattachment',
            name='attachment_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('worksheet', 'Работен лист'), ('rubric', 'Оценъчна карта / Чек-лист'), ('exit_ticket', 'Изходен билет'), ('task', 'Задача'), ('test', 'Тест'), ('self_study', 'Самостоятелна работа'), ('other', 'Други')], default='other', max_length=20, verbose_name='Тип'),
        ),
    ]
