# Generated by Django 4.2.24 on 2026-09-30 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0055_session_author_sessionattachment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('message', models.TextField(verbose_name='Текст на съобщението')),
                ('target_role', models.PositiveSmallIntegerField(choices=[(0, 'Всички потребители'), (4, 'Учители'), (5, 'Ученици'), (1, 'Администратори')], default=0, help_text='Роля на потребителите, до които е адресирано съобщението', verbose_name='Целева група')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Валидно до')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Създадено от')),
            ],
            options={
                'verbose_name': 'Броадкаст съобщение',
                'verbose_name_plural': 'Броадкаст съобщения',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочетено на')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='main.broadcastmessage', verbose_name='Съобщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Потребител')),
            ],
            options={
                'verbose_name': 'Прочетено броадкаст съобщение',
                'verbose_name_plural': 'Прочетени броадкаст съобщения',
            },
        ),
        migrations.AddConstraint(
            model_name='broadcastmessageread',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_user_broadcast_read'),
        ),
    ]
